x-gazebo-simulation: &simulation
  extends:
    file: compose.yaml
    service: world
  runtime: nvidia
  environment:
    NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics  # Allow GPU access
    NVIDIA_VISIBLE_DEVICES: all  # Expose all GPUs

services:
  world:
    <<: *simulation
    command: ros2 launch robotnik_gazebo_ignition spawn_world.launch.py
  spawn:
    <<: *simulation
    command: ros2 launch robotnik_gazebo_ignition spawn_robot.launch.py robot_id:=robot_a robot:=rbwatcher

volumes:
  tmp:
