services:
  robotnik_simulator:
    container_name: robotnik_simulator
    image: robotnik_simulation-robotnik_simulation:latest
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        base_image: robotnik/ros
        ros_distro: jazzy
        image_base_version: 0.6.2
        ros_mirror: ros.mirror.robotnik.ws
    network_mode: host
    privileged: true
    runtime: nvidia
    environment:
      ROS_DOMAIN_ID: 0
      DISPLAY: ${DISPLAY}  # Forward X11 display
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics  # Allow GPU access
      NVIDIA_VISIBLE_DEVICES: all  # Expose all GPUs
    devices:
      - "/dev/dri:/dev/dri"  # Allow OpenGL rendering
      - /tmp/.X11-unix:/tmp/.X11-unix
  robotnik_robot_spawner:
    container_name: robotnik_robot_spawner
    image: robotnik_simulation-robotnik_simulation:latest
    network_mode: host
    privileged: true
    runtime: nvidia
    env_file:
      - env/robot.env
    environment:
      ROS_DOMAIN_ID: 0
      DISPLAY: ${DISPLAY}  # Forward X11 display
      NVIDIA_DRIVER_CAPABILITIES: compute,utility,graphics  # Allow GPU access
      NVIDIA_VISIBLE_DEVICES: all  # Expose all GPUs
      ROBOT: rbkairos
      ROBOT_MODEL: rbkairos_plus
      HAS_ARM: true
      ROBOT_ID: robot
      ARM_TYPE: ur10e
      X_SPAWN: 0.0
      Y_SPAWN: 0.0
      Z_SPAWN: 0.0
      RUN_RVIZ: true
      RUN_MOVEIT: true
      MOVEIT_CONFIG_NAME: rbkairos_moveit_config
      ROS_BU_LAUNCH: spawn_robot.launch.py robot:=$${ROBOT} robot_model:=$${ROBOT_MODEL} has_arm:=$${HAS_ARM} robot_id:=$${ROBOT_ID} arm_type:=$${ARM_TYPE} x:=$${X_SPAWN} y:=$${Y_SPAWN} z:=$${Z_SPAWN} run_rviz:=$${RUN_RVIZ} run_moveit:=$${RUN_MOVEIT} moveit_config_name:=$${MOVEIT_CONFIG_NAME}
    devices:
      - "/dev/dri:/dev/dri"  # Allow OpenGL rendering
      - /tmp/.X11-unix:/tmp/.X11-unix
    depends_on:
      robotnik_simulator:
        condition: service_healthy

    volumes:
      - ./entrypoint.sh:/usr/local/bin/ros_entrypoint.sh
   

