<?xml version="1.0"?>
<package format="2">
  <name>robot_sim</name>
  <version>1.1.0</version>
  <description>The robot_sim package</description>

  <maintainer email="rvasquez@robotnik.es">Robert Vásquez</maintainer>
  <maintainer email="rnavarro@robotnik.es">Román Navarro</maintainer>


  <license>BSD</license>

  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>joint_state_controller</build_depend>
  <build_depend>velocity_controllers</build_depend>
  <build_depend>diff_drive_controller</build_depend>
  <build_depend>gripper_action_controller</build_depend>


  <!-- The export tag contains other, unspecified, tags -->
  <export>
    <!-- Other tools can request additional information be placed here -->

  </export>
</package>
